# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# SGeMS_ArcGIS.py
# Created on: 2020-03-09 19:37:50.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: SGeMS_ArcGIS <Input_ASCII_raster_file> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_ASCII_raster_file = arcpy.GetParameterAsText(0)

# Local variables:
Output_raster = ""
Output_Raster_Dataset = ""
Delete_succeeded = "false"

# Process: ASCII to Raster
arcpy.ASCIIToRaster_conversion(Input_ASCII_raster_file, Output_raster, "INTEGER")

# Process: Mirror
arcpy.Mirror_management(Output_raster, Output_Raster_Dataset)

# Process: Delete
arcpy.Delete_management(Output_raster, "")

